export const GET_LIST_BREADCRUMBS = 'GET_LIST_BREADCRUMBS';
export const GET_RECIPE_LIST_BREADCRUMBS = 'GET_RECIPE_LIST_BREADCRUMBS';
export const GET_ARTICLE_LIST_BREADCRUMBS = 'GET_ARTICLE_LIST_BREADCRUMBS';
export const LIST_BREADCRUMBS = 'LIST_BREADCRUMBS';
